### PR TITLE
DDT-706: Fix limit test

### PR DESCRIPTION
**Pull request by nt-as**
Signed-off-by: Niels Thykier <nt@asseco.dk>

### CODE REVIEW

**Comment by mp-assco** [comment]
Wouldn't it be simpler to only change `equalTo(limit)` to `lessThanOrEqualTo(limit)` and keep the rest as is?

**Comment by nt-as** [comment]
> Wouldn't it be simpler to only change `equalTo(limit)` to `lessThanOrEqualTo(limit)` and keep the rest as is?

Maybe, but then we would not assert that `limit=2` returns 2 results when we know there are at least two.  As in, if the API returned an empty list, the test would succeed but it has failed the  API contract.

**Comment by mp-assco** [comment]
> > Wouldn't it be simpler to only change `equalTo(limit)` to `lessThanOrEqualTo(limit)` and keep the rest as is?
> 
> Maybe, but then we would not assert that `limit=2` returns 2 results when we know there are at least two. As in, if the API returned an empty list, the test would succeed but the implementation has failed the API contract.

Fair enough.

**Review by mp-assco — APPROVED** [review]
lgtm

**Pull request merged**
